In [ ]:
import nltk
import pandas as pd
import numpy as np
import math
from nltk import pos_tag
import matplotlib.pyplot as plt
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from sklearn import datasets
from nltk.corpus import stopwords
import random
import string
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.tokenize import TreebankWordTokenizer
import pickle

In [ ]:
data=pd.read_excel('FeedbackDataset.xlsx')
data=np.array(data)
random.shuffle(data)
data=pd.DataFrame(data)
data

0  1
0   It was a good experience. I like it. It was no...  0
1                                It was a busy route.  0
2                                It was a busy route.  0
3   Good lighting conditions, moderate amount of p...  0
4                                   Safe, comfortable  0
..                                                ... ..
56                                  It was not good .  0
57  Women are free to go anywhere , it doesn't dep...  0
58  The street lights weren't working. There were ...  1
59  There is no such route to be described as safe...  0
60                                  Happens everyday   0

[61 rows x 2 columns]

In [ ]:
y_train=data[1]
x_train=data.loc[:,[0]]
x_train.iloc[:,0]

0     It was a good experience. I like it. It was no...
1                                  It was a busy route.
2                                  It was a busy route.
3     Good lighting conditions, moderate amount of p...
4                                     Safe, comfortable
                            ...                        
56                                    It was not good .
57    Women are free to go anywhere , it doesn't dep...
58    The street lights weren't working. There were ...
59    There is no such route to be described as safe...
60                                    Happens everyday 
Name: 0, Length: 61, dtype: object

In [ ]:
stopWords = stopwords.words('english')
punct=list(string.punctuation)
lemm = WordNetLemmatizer()
stopWords=stopWords+punct
stopWords.remove('no')
stopWords.remove('nor')
stopWords.remove('not')
stopWords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
def all_words(doc):
    l1=(word_tokenize(doc))
    final_doc=[]
    for l in l1:
        l=''.join([i for i in l if not i.isdigit()])
        for c in string.punctuation:
           l=l.replace(c,"")
        if len(l)>=3:
            if l.lower() not in stopWords:
                final_doc.append(l.lower())
    return(final_doc)

In [ ]:
nltk.download('punkt')
# data=[]
# for i in range(x_train.shape[0]):
#     sentence=all_words(x_train.iloc[i,0])
#     data.append((" ".join(sentence)))
# data
data=[]
for i in range(x_train.shape[0]):
    print(x_train.iloc[i,0])  # add this line to check input
    sentence=all_words(x_train.iloc[i,0])
    data.append((" ".join(sentence)))
data


It was a good experience. I like it. It was not lit although.
It was a busy route.
It was a busy route.
Good lighting conditions, moderate amount of pedestrians, good public transport connectivity.
Safe, comfortable
It was a busy route.
It was not good .
What remark in feedback would you give to express that a particular route is unsafe for women?
Unsafe, uncomfortable
Safe, comfortable
Easily available public transport.
Easily available public transport.
Prior history of assaults, no lights, isolated area with low human settlements
The place is gloomy, dark, and goes to a jungle
The route was not well lit.It is unsecure to travel at night.
It was a busy route.
The place is gloomy, dark, and goes to a jungle
Compromised security on this route 
Not Working street lamps, uncrowded route
This won't be so safe for this time of the day with that dress right now. PS I am a feminist this is just honest answers to convey something while bieng funny and not very grim or serious  
Den of thieves

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['good experience like not lit although',
 'busy route',
 'busy route',
 'good lighting conditions moderate amount pedestrians good public transport connectivity',
 'safe comfortable',
 'busy route',
 'not good',
 'remark feedback would give express particular route unsafe women',
 'unsafe uncomfortable',
 'safe comfortable',
 'easily available public transport',
 'easily available public transport',
 'prior history assaults lights isolated area low human settlements',
 'place gloomy dark goes jungle',
 'route not well litit unsecure travel night',
 'busy route',
 'place gloomy dark goes jungle',
 'compromised security route',
 'not working street lamps uncrowded route',
 'safe time day dress right feminist honest answers convey something bieng funny not grim serious',
 'den thieves people sorts sunsaan',
 'busy route',
 'easily available public transport',
 'prior history assaults lights isolated area low human settlements',
 'dim light conditions poor signal reception close tobacco a

In [ ]:
document=[]
for i in range(y_train.shape[0]):
    document.append((data[i],y_train[i]))
document

[('good experience like not lit although', 0),
 ('busy route', 0),
 ('busy route', 0),
 ('good lighting conditions moderate amount pedestrians good public transport connectivity',
  0),
 ('safe comfortable', 0),
 ('busy route', 0),
 ('not good', 0),
 ('remark feedback would give express particular route unsafe women', 0),
 ('unsafe uncomfortable', 0),
 ('safe comfortable', 0),
 ('easily available public transport', 0),
 ('easily available public transport', 0),
 ('prior history assaults lights isolated area low human settlements', 0),
 ('place gloomy dark goes jungle', 0),
 ('route not well litit unsecure travel night', 0),
 ('busy route', 0),
 ('place gloomy dark goes jungle', 0),
 ('compromised security route', 0),
 ('not working street lamps uncrowded route', 0),
 ('safe time day dress right feminist honest answers convey something bieng funny not grim serious',
  0),
 ('den thieves people sorts sunsaan', 0),
 ('busy route', 0),
 ('easily available public transport', 0),
 ('prior hi

In [ ]:
random.shuffle(document)
train=document[:91]
train

[('busy route', 0),
 ('safe comfortable', 0),
 ('compromised security route', 0),
 ('women free anywhere depend route depends mentality society change everything fine',
  0),
 ('compromised security route', 0),
 ('busy route', 0),
 ('good lighting conditions moderate amount pedestrians good public transport connectivity',
  0),
 ('busy route', 0),
 ('route street lights', 0),
 ('busy route', 0),
 ('good lighting conditions moderate amount pedestrians good public transport connectivity',
  0),
 ('boys unsafe dammnit wamens stop one gives shit', 0),
 ('route not well litit unsecure travel night', 0),
 ('place gloomy dark goes jungle', 0),
 ('completely illlighting irrespective presence cctv camera', 0),
 ('unsafe uncomfortable', 0),
 ('compromised security route', 0),
 ('', 0),
 ('street lights working cameras poor mobile network wifi also narrow lonely',
  1),
 ('lack police service', 1),
 ('easily available public transport', 0),
 ('easily available public transport', 0),
 ('dim light 

In [ ]:
xtrain=[]
ytrain=[]
for i in (train):
    xtrain.append(i[0])
    ytrain.append(i[1])
xtrain

['busy route',
 'safe comfortable',
 'compromised security route',
 'women free anywhere depend route depends mentality society change everything fine',
 'compromised security route',
 'busy route',
 'good lighting conditions moderate amount pedestrians good public transport connectivity',
 'busy route',
 'route street lights',
 'busy route',
 'good lighting conditions moderate amount pedestrians good public transport connectivity',
 'boys unsafe dammnit wamens stop one gives shit',
 'route not well litit unsecure travel night',
 'place gloomy dark goes jungle',
 'completely illlighting irrespective presence cctv camera',
 'unsafe uncomfortable',
 'compromised security route',
 '',
 'street lights working cameras poor mobile network wifi also narrow lonely',
 'lack police service',
 'easily available public transport',
 'easily available public transport',
 'dim light conditions poor signal reception close tobacco alcohol shops',
 'easily available public transport',
 'happens everyday

In [ ]:

from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer(max_features=3200)
data1 = vec.fit_transform(xtrain).toarray()
print(data1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
xtrain=pd.DataFrame(data1)

In [ ]:
ytrain=pd.DataFrame(ytrain)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [ ]:
rf=RandomForestClassifier()
rf.fit(xtrain,ytrain)
rf.score(xtrain,ytrain)

<ipython-input-43-697f77b1c204>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(xtrain,ytrain)


1.0

In [ ]:
l=LogisticRegression(fit_intercept=False)
l.fit(xtrain,ytrain)
l.score(xtrain,ytrain)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0

In [ ]:
d=DecisionTreeClassifier()
d.fit(xtrain,ytrain)
d.score(xtrain,ytrain)

1.0

In [ ]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
g=BernoulliNB()
g.fit(xtrain,ytrain)
g.score(xtrain,ytrain)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9836065573770492

In [ ]:
def predict_safety(remark):
    datta=[]
    sentence=all_words(remark)
    datta.append((" ".join(sentence)))
    documentt=[]
    documentt.append(datta)
    ttrain = documentt[:]
    xttrain=[]
    for i in (ttrain):
        xttrain.append(i[0])
    datta1=vec.transform(xttrain).toarray()
    xttrain=pd.DataFrame(datta1)
    return str(l.predict(xttrain)[0])

In [ ]:
predict_safety("it is unsafe and not well lit")

'0'