In [ ]:
pip install bs4

In [ ]:
import pandas as pd
import numpy as np
import requests
data = pd.read_csv("streets_detail.csv",encoding = "ISO-8859-1")
print(data.head())
streets= np.array(data['Sreet name'])[1:]
streets=np.array(streets)
data=np.array(data)
print(streets)

                Sreet name  ...    district
0                      NaN  ...         NaN
1               Akbar road  ...     central
2      Aruna Asaf Ali Marg  ...  south west
3             Ashram Chowk  ...  south west
4  Bahadur Shah Zafar Marg  ...     central

[5 rows x 15 columns]
['Akbar road' 'Aruna Asaf Ali Marg' 'Ashram Chowk'
 'Bahadur Shah Zafar Marg' 'Barakhamba Road' 'Delhi Gurgaon Expressway'
 'DND Flyway' 'Dr APJ Abdul Kalam Road'
 'Eastern Peripheral Expressway (NE II)'
 'Faridabad-Noida-Ghaziabad Expressway' 'Grand Trunk Road' 'IIT Flyover'
 'Inner Ring Road, Delhi' 'Janpath Road' 'Kashmiri Gate, Delhi'
 'Lodhi Road' 'Lok Kalyan Marg' 'Mathura Road, Delhi'
 'Outer Ring Road, Delhi' 'Mansingh Road' 'Motilal Nehru Road'
 'Maulana Azad Road' 'Krishna Menon Road' 'Tughlaq Road'
 'Tees January Marg' 'Delhi Ring Road' 'Shahjahan Road' 'Humayun Road'
 'Prithviraj Road' 'Mustafa Kemal Ataturk Marg' 'Safdarjung Road'
 'National Highway 1' 'National Highway 2' 'National Highway 

In [ ]:
st='a'
len(st)

1

In [ ]:
m=np.zeros(len(streets))
c=2
for street in streets:
  c+=1
  try:
    wiki = "https://www.google.com/search?q="+street+' nearest metro station'
    wiki=wiki.replace(' ','%20')
    #print(wiki)
    import requests
    page=requests.get(wiki).text
    from bs4 import BeautifulSoup

    soup = BeautifulSoup(page, 'html.parser')
    #print(soup.prettify())
    div=soup.find_all('div',{'class':'am3QBf'})
    #print(div[0].text)
    imp=div[0].find_all('div',{'class':'BNeawe deIvCb AP7Wnd'})
    if len(imp[0].text)==1:
      imp=imp[1].text
    else:
      imp=imp[0].text
    #print(imp)
    wiki = "https://www.google.com/search?q=distance of "+street+' to '+imp +' metro station'
    wiki=wiki.replace(' ','%20')
    #print(wiki)

    page=requests.get(wiki).text

    soup = BeautifulSoup(page, 'html.parser')
    #print(soup.prettify())
    #f=open("abc.html","w+")
    #f.write(str(soup))

    div=soup.find_all('div',{'class':'BNeawe deIvCb AP7Wnd'})[0].text
    #print(div)
    div=div.replace('(','zzzz')
    div=div.replace(')','zzzz')
    import re
    m=re.search('zzzz(.+?)zzzz', div).group(1)
    print(m)
    if ' m' in m:
      m = float(m.replace(' m',''))/1000
    else:
      m = float(m.replace(' km',''))
    #print(m)
  except:
    print(' ')

26.5 km
 
5.0 km
3.2 km
 
750.0 m
 
 
800.0 m
 
 
 
 
 
280.0 m
 
 
8.1 km
 
1.2 km
 
 
3.2 km
 
2.8 km


In [ ]:
data=np.array(data[116:])
print(data)
x = data[:,3]
#x=x[1:]
print(x)

[['Mehrauli Badarpur Road' '26.5' 'major district road' 'south' '4.8' nan
  nan nan nan nan nan nan nan nan]
 ['Aurbindo Marg' '0.55' 'major district road' 'south west' '1.1' nan nan
  nan nan nan nan nan nan nan]
 ['Mahipalpur Mehrauli Road' '5' 'major district road' 'south west' '8.8'
  nan nan nan nan nan nan nan nan nan]
 ['Mehrauli  Gurgaon Road' '3.2' 'major district road' 'south west' '6.5'
  nan nan nan nan nan nan nan nan nan]
 ['Ho Chi Minh Marg' '0.152' 'major district road' 'south' '0.45' nan nan
  nan nan nan nan nan nan nan]
 ['Lala Lajpat Rai Marg' '0.75' 'major district road' 'south' '1.8' nan
  nan nan nan nan nan nan nan nan]
 ['Lal Bahadur Shastri Marg' '0.16' 'major district road' 'south' '6.7'
  nan nan nan nan nan nan nan nan nan]
 ['Shanti Path' '0.455' 'major district road' 'south west' '0.8' nan nan
  nan nan nan nan nan nan nan]
 ['Pusa Road' '0.8' 'major district road' 'central' '1.1' nan nan nan nan
  nan nan nan nan nan]
 ['Cariappa Marg' '1' 'major distric

In [ ]:
population = np.zeros(len(x))
for i in range(0,len(x)):
  x[i] = x[i].lower()
  if x[i]=='south':
    population[i] = 2731929
  if x[i]=='central':
    population[i] = 582320
  if x[i]=='north':
    population[i] = 887978
  if x[i]=='north east':
    population[i] = 2241624
  if x[i]=='north west':
    population[i] = 3656539
  if x[i]=='south west':
    population[i] = 2292958
  if x[i]=='west':
    population[i] = 2543243
  if x[i]=='east':
    population[i] = 1709346
  if x[i]=='new delhi':
    population[i] = 142004
  if x[i]=='delhi cantt':
    population[i] = 116000
  print(population[i])

2731929.0
2292958.0
2292958.0
2292958.0
2731929.0
2731929.0
2731929.0
2292958.0
582320.0
116000.0
2292958.0
582320.0
2731929.0
582320.0
582320.0
2543243.0
2292958.0
2292958.0
582320.0
582320.0
2292958.0
582320.0
582320.0
2292958.0
2292958.0


In [ ]:
import pandas as pd
import numpy as np
import requests
crime = np.array(pd.read_csv("crime.csv"))
print(crime)

[['Central' 91 305 212 54 9 26 123 37]
 ['East' 230 678 446 171 36 91 143 114]
 ['New Delhi' 20 44 56 25 1 14 15 18]
 ['North' 60 279 180 42 12 16 109 18]
 ['North East' 237 1047 492 171 46 47 224 50]
 ['North West' 165 663 404 109 23 61 208 51]
 ['South' 280 627 595 150 39 0 406 665]
 ['South East' 266 683 469 85 34 74 274 123]
 ['South West' 234 719 494 86 57 99 248 68]
 ['West' 251 848 484 137 64 52 223 63]]


In [ ]:
print(x)

['south' 'south west' 'south west' 'south west' 'south' 'south' 'south'
 'south west' 'central' 'delhi cantt' 'south west' 'central' 'south'
 'central' 'central' 'west' 'south west' 'south west' 'central' 'central'
 'south west' 'central' 'central' 'south west' 'south west']


In [ ]:
for dis in x:
  flag=0
  for i in crime:

    if dis.lower() == i[0].lower():
      flag=1
      print(i[8])
  if flag==0:
    print('0')

665
68
68
68
665
665
665
68
37
0
68
37
665
37
37
63
68
68
37
37
68
37
37
68
68


In [ ]:
data=np.array(data[116:])

In [ ]:
data=data[1:]
print(data)

[['Akbar road' 1.2 'major district road' ... 123.0 37.0 'central']
 ['Aruna Asaf Ali Marg' 5.1 'district road' ... 248.0 68.0 'south west']
 ['Ashram Chowk' 5.7 'major district road' ... 274.0 123.0 'south west']
 ...
 ['Ashoka Road' 3.2 'major district road' ... 123.0 37.0 'central']
 ['Sree Vinayaka Mandir Marg' 0.6 'major district road' ... 248.0 68.0
  'south west']
 ['Kautilya Marg' 2.8 'major district road' ... 248.0 68.0 'south west']]


In [ ]:
c=1
for street in streets:
  try:
    wiki = "https://www.google.com/search?q="+street+' nearest police station'
    wiki=wiki.replace(' ','%20')
    #print(wiki)
    import requests
    page=requests.get(wiki).text
    from bs4 import BeautifulSoup
    #print(page)
    soup = BeautifulSoup(page, 'html.parser')
    '''
    f=open("xyz.html","w+")
    f.write(str(soup))
    '''
    #print(soup.prettify())
    try:
      div=soup.find_all('div',{'class':'am3QBf'})
    except:
      None 
    #print(div[0].text)
    flag=0
    try:
      imp=div[0].find_all('div',{'class':'BNeawe deIvCb AP7Wnd'})
    except:
      imp=soup.find_all('div',{'class':'BNeawe s3v9rd AP7Wnd'})
      flag=1
    if len(imp[0].text)==1 or flag==1:
      imp=imp[1].text
    else:
      imp=imp[0].text
    #print(imp)
    wiki = "https://www.google.com/search?q=distance of "+street+' to '+imp 
    wiki=wiki.replace(' ','%20')
    #print(wiki)

    page=requests.get(wiki).text

    soup = BeautifulSoup(page, 'html.parser')
    #print(soup.prettify())
    #f=open("abc.html","w+")
    #f.write(str(soup))
    try:
      div=soup.find_all('div',{'class':'BNeawe deIvCb AP7Wnd'})[0].text
    except:
      div=soup.find_all('div',{'class':'BNeawe s3v9rd AP7Wnd'})[0].text
    #print(div)
    div=div.replace('(','zzzz')
    div=div.replace(')','zzzz')
    import re
    m=re.search('zzzz(.+?)zzzz', div).group(1)
    if ' m' in m:
      m = float(m.replace(' m',''))/1000
    else:
      m = float(m.replace(' km',''))
    print(m)
    
  except:
    print(' ')
  c+=1

4.8
 
8.8
6.5
 
 
6.7
 
1.1
2.7
 
0.9
 
 
0.4
 
 
10.5
 
5.5
 
 
 
 
1.1


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import random
from tqdm import tqdm
import numpy as np
from sklearn.datasets.samples_generator import make_blobs
from sklearn.cluster import SpectralClustering, AffinityPropagation

In [ ]:
 '''import numpy as np
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))'''
import utils
fin = data[:,1:6]
print(fin[:,1])

['major district road' 'district road' 'major district road'
 'major district road' 'major district road' 'expressway'
 'major district road' 'major district road' 'expressway' 'expressway'
 'major district road' 'flyover' 'major district road'
 'major district road' 'major district road' 'major district road'
 'major district road' 'major district road' 'major district road'
 'district road' 'district road' 'district road' 'district road'
 'district road' 'district road' 'Ring road' 'major district road'
 'district road' 'major district road' 'major district road'
 'major district road' 'national highway' 'national highway'
 'national highway' 'national highway' 'national highway'
 'major district road' 'flyover' 'district road' 'flyover'
 'major district road' 'major district road' 'district road' 'flyover'
 'flyover' 'flyover' 'flyover' 'flyover' 'flyover' 'district road'
 'district road' 'flyover' 'flyover' 'flyover' 'flyover'
 'major district road' 'major district road' 'major dis

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
fin[:,1] = label_encoder.fit_transform(fin[:,1])

In [ ]:
print(fin)

[[1.2 6 857.0 2.5 582320.0]
 [5.1 2 2005.0 17.4 2292958.0]
 [5.7 6 2008.0 2.7 2292958.0]
 [0.27 6 857.0 2.6 582320.0]
 [2.4 6 857.0 0.39299999999999996 582320.0]
 [8.2 3 0.0 4.6 2543243.0]
 [13.0 6 0.0 13.3 1674714.0]
 [0.5 6 857.0 0.65 582320.0]
 [90.6 3 0.0 20.1 1674714.0]
 [6.1 3 0.0 4.8 1674714.0]
 [0.141 6 2314.0 45.0 2241624.0]
 [0.157 4 2762.0 4.2 2731929.0]
 [9.2 6 2314.0 18.2 2241624.0]
 [1.2 6 857.0 0.7 582320.0]
 [0.7 6 857.0 1.5 582320.0]
 [3.5 6 857.0 1.1 582320.0]
 [1.6 6 857.0 2.5 582320.0]
 [3.2 6 2762.0 14.8 2731929.0]
 [1.1 6 1684.0 4.0 3656539.0]
 [2.0 2 857.0 2.5 582320.0]
 [1.3 2 857.0 2.0 582320.0]
 [0.20199999999999999 2 857.0 0.5 582320.0]
 [0.47200000000000003 2 2005.0 0.792 2292958.0]
 [0.047 2 857.0 0.23 582320.0]
 [1.2 2 857.0 1.4 582320.0]
 [2.1 0 0.0 14.2 0.0]
 [2.6 6 857.0 1.7 582320.0]
 [0.55 2 857.0 0.4 582320.0]
 [1.0 6 857.0 1.6 582320.0]
 [0.7859999999999999 6 0.0 40.0 2731929.0]
 [1.6 6 857.0 1.6 582320.0]
 [197.0 7 2762.0 600.0 2731929.0]
 [600.0 7

In [ ]:
clustering = SpectralClustering(n_clusters=4, assign_labels="discretize", random_state=0).fit(fin)
y_pred = clustering.labels_

/usr/local/lib/python3.6/dist-packages/sklearn/manifold/spectral_embedding_.py:235: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


In [ ]:
for i in y_pred:
  print(i)

3
2
1
3
3
3
1
3
3
1
3
0
0
3
3
3
3
0
1
3
3
3
1
3
3
3
3
3
3
2
3
3
2
0
0
0
0
3
3
3
1
0
1
1
1
3
2
1
1
1
1
1
1
1
2
3
0
0
0
0
0
0
3
3
3
3
3
1
3
3
3
3
3
3
0
3
3
1
1
2
1
1
3
1
3
3
0
3
3
3
3
0
1
1
1
0
1
3
0
3
1
3
1
3
0
3
3
1
1
1
1
3
3
1
1
2
1
2
2
0
0
0
1
3
1
1
3
0
3
3
1
1
2
3
3
1
3
3
1
1


In [ ]:
# k nearest neighbors
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(fin, y_pred) 
print(neigh.predict([[1.6,4,550,3,582320.0]]))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
import json
d=[[1.6,4,550,3,582320.0]]
d=json.dumps(d)
print(d)

[[1.6, 4, 550, 3, 582320.0]]
